[[items]]
"name" = "★ Falchion Knife | Tiger Tooth (Factory New)"
"price" = 161.00
"game_id" = 730

[[items]]
"name" = "AK-47 | Fuel Injector (Battle-Scarred)"
"price" = 92.18
"game_id" = 730

[[items]]
"name" = "M4A1-S | Golden Coil (Well-Worn)"
"price" = 32.50
"game_id" = 730

[[items]]
"name" = "USP-S | The Traitor (Well-Worn)"
"price" = 12.01
"game_id" = 730

[[items]]
"name" = "AWP | Chromatic Aberration (Minimal Wear)"
"price" = 42.22
"game_id" = 730

[[items]]
"name" = "Sir Bloody Darryl Royale | The Professionals"
"price" = 24.65
"game_id" = 730